
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:laza/providers/auth_provider.dart';
import 'package:laza/providers/cart_provider.dart';      // ADD THIS
import 'package:laza/providers/favorites_provider.dart'; // ADD THIS
import 'package:laza/splash_screen.dart';
import 'package:laza/theme.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';  // Generated by flutterfire configure
import 'package:laza/providers/auth_provider.dart' as laza_auth;


void main() async {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,
);
runApp(const MyApp());
}

class MyApp extends StatelessWidget {
const MyApp({super.key});

@override
Widget build(BuildContext context) {
return MultiProvider(
providers: [
ChangeNotifierProvider(create: (_) => ThemeNotifier()),
ChangeNotifierProvider(create: (_) => AuthProvider()),
// ADD THESE TWO PROVIDERS:
ChangeNotifierProvider(create: (_) => CartProvider()),
ChangeNotifierProvider(create: (_) => FavoritesProvider()),
  ChangeNotifierProvider(create: (_) => laza_auth.AuthProvider()),

],
child: Consumer<ThemeNotifier>(
builder: (context, themeNotifier, child) {
return MaterialApp(
title: 'Laza',
debugShowCheckedModeBanner: false,
themeMode: themeNotifier.themeMode,
theme: AppTheme.lightTheme,
darkTheme: AppTheme.darkTheme,
home: const SplashScreen(),
);
},
),
);
}
}
